swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for user login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for user signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch user profile
      description: API for fetching a user profile
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this resource
        "404":
          description: Not Found - User profile not found
        "400":
          description: Invalid fields
        "500":
          description: Internal server error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update user profile
      description: API for updating a user profile
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this resource
        "404":
          description: Not Found - User profile not found
        "400":
          description: Invalid fields
        "500":
          description: Internal server error

  /user/accounts/{accountId}:
    get:
      tags:
        - User Transactions
      summary: Get user's account
      description: API for getting a user's account
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
      produces:
        - application/json
      responses:
        "200":
          description: Account retrieved successfully
          schema:
            $ref: "#/definitions/AccountsResponse"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this account
        "404":
          description: Not Found - Account not found
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions:
    get:
      tags:
        - User Transactions
      summary: Get account transactions
      description: API for getting account transactions
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: Account ID
        - name: fromMonth
          in: query
          type: string
          required: false
          description: Start month for fetching transactions (YYYY-MM)
        - name: toMonth
          in: query
          type: string
          required: false
          description: End month for fetching transactions (YYYY-MM)
      produces:
        - application/json
      responses:
        "200":
          description: Account transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this account
        "404":
          description: Not Found - Account or transactions not found
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - User Transactions
      summary: Get transaction details
      description: API for getting a single transaction details
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
        - name: transactionId
          in: path
          type: integer
          required: true
          description: Transaction's ID
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this transaction
        "404":
          description: Not Found - Transaction not found
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions/{transactionId}/category:
    patch:
      tags:
        - User Transactions
      summary: Update transaction category
      description: API for updating a transaction's category
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
        - name: transactionId
          in: path
          type: integer
          required: true
          description: Transaction's ID
        - name: body
          in: body
          required: true
          description: Update transaction's category
          schema:
            $ref: "#/definitions/TransactionsUpdateCategory"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this transaction
        "404":
          description: Not Found - Transaction not found
        "400":
          description: Bad request. User ID/transaction ID must be an integer and larger than 0
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions/{transactionId}/notes:
    patch:
      tags:
        - User Transactions
      summary: Update transaction notes
      description: API for updating transaction's notes
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
        - name: transactionId
          in: path
          type: integer
          required: true
          description: Transaction's ID
        - name: body
          in: body
          required: true
          description: Update transaction's notes
          schema:
            $ref: "#/definitions/TransactionsUpdateNotes"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Transaction notes updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this transaction
        "404":
          description: Not Found - Transaction not found
        "400":
          description: Bad request. User ID/transaction ID must be an integer and larger than 0
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions/{transactionId}/category/delete:
    delete:
      tags:
        - User Transactions
      summary: Delete transaction category
      description: API for deleting a transaction's category
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
        - name: transactionId
          in: path
          type: integer
          required: true
          description: Transaction's ID
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "204":
          description: Transaction category deleted successfully
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this transaction
        "404":
          description: Not Found - Transaction not found
        "400":
          description: Bad request. User ID/transaction ID must be an integer and larger than 0
        "500":
          description: Internal server error
      security:
        - Bearer: []

  /user/accounts/{accountId}/transactions/{transactionId}/notes/delete:
    delete:
      tags:
        - User Transactions
      summary: Delete transaction notes
      description: API for deleting transaction's notes
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
          description: Bearer JWT token
        - name: accountId
          in: path
          type: integer
          required: true
          description: User's account ID
        - name: transactionId
          in: path
          type: integer
          required: true
          description: Transaction's ID
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "204":
          description: Transaction notes deleted successfully
        "401":
          description: Unauthorized - Invalid or missing authentication token
        "403":
          description: Forbidden - User does not have access to this transaction
        "404":
          description: Not Found - Transaction not found
        "400":
          description: Bad request. User ID/transaction ID must be an integer and larger than 0
        "500":
          description: Internal server error
      security:
        - Bearer: []

definitions:
  Login:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  LoginResponse:
    type: object
    properties:
      token:
        type: string
      user:
        $ref: "#/definitions/User"

  ApiResponse:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  User:
    type: object
    required:
      - email
      - password
      - firstName
      - lastName
    properties:
      id:
        type: integer
      email:
        type: string
        format: email
      password:
        type: string
        format: password
      firstName:
        type: string
      lastName:
        type: string

  UserProfile:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
      lastName:
        type: string

  AccountsResponse:
    type: object
    properties:
      accounts:
        type: array
        items:
          $ref: "#/definitions/Account"

  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      balance:
        type: number
        format: double
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"

  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"

  Transaction:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      type:
        type: string
      category:
        type: string
      notes:
        type: string

  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string

  TransactionsUpdateNotes:
    type: object
    properties:
      notes:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
